### ISSUE TITLE
Cant choose dependencies

### ISSUE THREAD

**Issue by Agniusm** [somewherewarm/woocommerce-product-dependencies#10]
Hi. First, great plugin. I had it working but something went wrong and it does not work anymore. WP version 4.7.4, Woocommerce - 3.0.6
Dependencies box displays previously entered dependencies in this format: XXXXXX(#XXX). Does not respond to clicks
![wcdp](https://cloud.githubusercontent.com/assets/28608065/25919186/93040df2-35d6-11e7-80eb-298682c8beab.png)

Any help appreciated
P.S. Tried downgrading WP to 4.7.3 and woocommerce to 3.0.5, reinstalling plugin, disabling all plugins but woocommerce and this one

**Comment by alicia250** [comment]
I'm having the same issue :(

**Comment by Agniusm** [comment]
I found my cause. It was social plugin. Disable recent installed plugins to see if it helps

**Comment by franticpsyx** [comment]
Yep, that's an issue with the `select2` library. 

WC uses version 4, but some plugins still load version 3, which breaks all search-powered WooCommerce fields.
