### ISSUE TITLE
Dependencies not honored

### ISSUE THREAD

**Issue by dlfdlf56** [somewherewarm/woocommerce-product-dependencies#11]
The plugin works as it should on the initial add of a restricted product to the cart, but if I add the required item and the dependent product and then remove the required product, it allows the sale to go through.

**Comment by franticpsyx** [comment]
Hey @dlfdlf56 

Thanks for the report! I am afraid I can't replicate the behavior you describe, though.

Here's what I see after removing the "required" product from the cart:

https://cl.ly/0C1l2W2v212S

When attempting to checkout:

https://cl.ly/443X370d3M3x

WC 3.0.8, PD 1.1.1

Closing, but feel free to provide more details! Thanks again!

**Comment by dlfdlf56** [comment]
Here is the picture of it working stating that it needs the dependent product:
![image](https://user-images.githubusercontent.com/29309591/27094076-8eb323e2-502e-11e7-88b5-14822daf44fa.png)

Here I have both products in the cart:
![image](https://user-images.githubusercontent.com/29309591/27094157-ce97244a-502e-11e7-9ba1-c5dc8e25b42e.png)

Here I removed the mandatory product:
![image](https://user-images.githubusercontent.com/29309591/27094189-e4846970-502e-11e7-88a4-c4b8526f9cf3.png)

Moving on to checkout: 
![image](https://user-images.githubusercontent.com/29309591/27094207-f592fd12-502e-11e7-8d72-665480597b0e.png)

And checkout complete with a brand new user that hasn't ordered anything previously.
![image](https://user-images.githubusercontent.com/29309591/27094240-108bdfb2-502f-11e7-8f00-80bdbb605d30.png)

**Comment by dlfdlf56** [comment]
I posted some screenshots showing the failure that I'm seeing.
