### ISSUE TITLE
Optional Product Dependencies

### ISSUE THREAD

**Issue by Valixx** [somewherewarm/woocommerce-product-dependencies#13]
Hey there.

Is it possible to add "Optional" to the Dependencie Type? So that the customer has the choice to add it or not. That would make me and my client very happy.

Cheers.

**Comment by franticpsyx** [comment]
@Valixx Can you describe a use case or example for this? A dependency is a purchase or ownership requirement, which means it can't be "optional".

**Comment by franticpsyx** [comment]
Closing -- sounds like you need something like https://github.com/somewherewarm/woocommerce-product-bundles-bundle-sells
