### ISSUE TITLE
WC 2.6: Fatal error when 'Ownership' or 'Either' Dependency Type is selected

### ISSUE THREAD

**Issue by jimjasson** [somewherewarm/woocommerce-product-dependencies#21]
To replicate this:

- Install WooCommerce v2.6 .

- In Product Dependencies select some products or categories.

- In the Dependency Type dropdown, select Ownership or Either.

- Click to view the product.

- Click 'Add to Cart'.

**Comment by franticpsyx** [comment]
@jimjasson what's the Fatal Error content? Did you find the cause?

**Comment by franticpsyx** [comment]
Closed via https://github.com/somewherewarm/woocommerce-product-dependencies/pull/24

Props to @jimjasson
