### ISSUE TITLE
Custom Notice cannot be deleted

### ISSUE THREAD

**Issue by jimjasson** [somewherewarm/woocommerce-product-dependencies#22]
Custom Notice field contents are not deleted even after leaving the field empty and clicking update.

To replicate this:

- In the Custom Notice field insert some text.

- Click 'Update'.

- Remove all contents from the Custom Notice field.

- Click 'Update'.

- Check if the Custom Notice field is empty.

**Comment by franticpsyx** [comment]
Closed via #23
