### ISSUE TITLE
Required product purchased, not recognized by store.

### ISSUE THREAD

**Issue by alicia250** [somewherewarm/woocommerce-product-dependencies#25]
Required product purchased about 10 orders and 50 items ago, but plugin does not recognize it as purchased. 

Deleted orders made after required purchase was made, still won't work.

Woocommerce Version 3.2.6

**Comment by franticpsyx** [comment]
Hey @alicia250 thanks for the issue report! 

Are you experiencing this with version `1.2.0-dev` from `master`?

**Comment by jimjasson** [comment]
Confirmed bug with the latest version of Product Dependencies.

**Comment by franticpsyx** [comment]
Thanks @jimjasson -- so this only affected the `master` branch then.

**Comment by franticpsyx** [comment]
@alicia250 this should be fixed in the latest `master` branch. Can you confirm?

**Comment by alicia250** [comment]
Since the update we've had no issues. :) I'll update if anything else pops
up.
