### ISSUE TITLE
Dependency on variable products

### ISSUE THREAD

**Issue by stevegrant1983** [somewherewarm/woocommerce-product-dependencies#41]
It seems as though the functionality for product dependency within variable products has been removed - is there any reason for this?

Previously, we were able to restrict access to a specific variation of a product so that they can only buy that if they are also buying a different specific variation of that same product, but now we can't do that.

Is there a way of restoring this functionality?

**Comment by franticpsyx** [comment]
Hey @stevegrant1983 thanks for opening an issue here!

@jimjasson could you please take a look?

**Comment by jimjasson** [comment]
Hey @stevegrant1983  👋🏻

In my local site, I installed the latest Product Dependencies version (v1.2.6). 

I was able to add a specific variation as a dependency to a Simple Product: https://a.cl.ly/Z4uoQl72. This is what I see when I try to add this Simple Product to the cart without first adding the dependent variation: https://a.cl.ly/NQuw2RjG. 

Is this not what you see? Is there a chance that variations do not show up in this search field: https://a.cl.ly/KoudvO9e?

>  so that they can only buy that if they are also buying a different specific variation of that same product, but now we can't do that.

Product Dependencies are set on product-level, not on variation-level. This means that you cannot add a Product Dependency to a specific variation, but only to the entire Variable Product. Setting variation-level dependencies was never possible as far as I remember -- @franticpsyx can you please confirm?

**Comment by stevegrant1983** [comment]
Hi @jimjasson

Thanks for investigating this. We definitely had event tickets (where there would be a number of age-based variations) set up which would then enable us to prevent the "purchase" of a child variation (the price of which was £0.00) without the purchase of an adult one.

The form that appears on the Product Dependencies tab weirdly showed at the top and bottom of each variation block in the Variations tab, which I just put down to a strange bug, but the functionality worked. Now those forms have disappeared.

**Comment by franticpsyx** [comment]
Hey @stevegrant1983 

The plugin hasn't received any minor/major changes in the last 3-4 years. Feel free to clone the repo and examine the commit tree.

> The form that appears on the Product Dependencies tab weirdly showed at the top and bottom of each variation block in the Variations tab

I can't recall coding something like this :) There's a chance that someone may have customized the plugin for you though?

**Comment by adamj7** [comment]
I'm not sure why this is closed...
I'm just installing this for the first time in my shop. I have 1 product, variable, with 3 variations [SingleRoot, Downstream, Disconnected]. I wish to use this plugin to require SingleRoot to be required in order to purchase a Downstream or Disconnected - Either with the current cart purchase or Ownership. Each time I try to put a dependency on my single product of the variation SingleRoot, it prevents any additions to cart of the any of the product variations, including SingleRoot
